
+--------+---------------------------------------------------------------+-----------------------------------+-------------------------------------------------------------------+-------------------------+---------------+
| Domain | URI                                                           | Name                              | Action                                                            | Before Filters          | After Filters |
+--------+---------------------------------------------------------------+-----------------------------------+-------------------------------------------------------------------+-------------------------+---------------+
|        | GET|HEAD _debugbar/open                                       | debugbar.openhandler              | Barryvdh\Debugbar\Controllers\OpenHandlerController@handle        |                         |               |
|        | GET|HEAD _debugbar/assets/stylesheets                         | debugbar.assets.css               | Barryvdh\Debugbar\Controllers\AssetController@css                 |                         |               |
|        | GET|HEAD _debugbar/assets/javascript                          | debugbar.assets.js                | Barryvdh\Debugbar\Controllers\AssetController@js                  |                         |               |
|        | GET|HEAD api/hardware/list/{status?}                          | api.hardware.list                 | Controllers\Admin\AssetsController@getDatatable                   | admin-auth              |               |
|        | POST api/hardware/import                                      |                                   | Controllers\Admin\AssetsController@postAPIImportUpload            | admin-auth              |               |
|        | GET|HEAD api/statuslabels                                     | api.statuslabels...index          | Controllers\Admin\StatuslabelsController@index                    | admin-auth              |               |
|        | GET|HEAD api/statuslabels/create                              | api.statuslabels...create         | Controllers\Admin\StatuslabelsController@create                   | admin-auth              |               |
|        | POST api/statuslabels                                         | api.statuslabels...store          | Controllers\Admin\StatuslabelsController@store                    | admin-auth              |               |
|        | GET|HEAD api/statuslabels/{}                                  | api.statuslabels...show           | Controllers\Admin\StatuslabelsController@show                     | admin-auth              |               |
|        | GET|HEAD api/statuslabels/{}/edit                             | api.statuslabels...edit           | Controllers\Admin\StatuslabelsController@edit                     | admin-auth              |               |
|        | PUT api/statuslabels/{}                                       | api.statuslabels...update         | Controllers\Admin\StatuslabelsController@update                   | admin-auth              |               |
|        | PATCH api/statuslabels/{}                                     |                                   | Controllers\Admin\StatuslabelsController@update                   | admin-auth              |               |
|        | DELETE api/statuslabels/{}                                    | api.statuslabels...destroy        | Controllers\Admin\StatuslabelsController@destroy                  | admin-auth              |               |
|        | GET|HEAD api/statuslabels/{statuslabelId}/deployable          |                                   | Closure                                                           | admin-auth              |               |
|        | GET|HEAD api/statuslabels/list                                | api.statuslabels.list             | Controllers\Admin\StatuslabelsController@getDatatable             | admin-auth              |               |
|        | GET|HEAD api/accessories/list                                 | api.accessories.list              | Controllers\Admin\AccessoriesController@getDatatable              | admin-auth              |               |
|        | GET|HEAD api/accessories/{accessoryID}/view                   | api.accessories.view              | Controllers\Admin\AccessoriesController@getDataView               | admin-auth              |               |
|        | GET|HEAD api/consumables/list                                 | api.consumables.list              | Controllers\Admin\ConsumablesController@getDatatable              | admin-auth              |               |
|        | GET|HEAD api/consumables/{consumableID}/view                  | api.consumables.view              | Controllers\Admin\ConsumablesController@getDataView               | admin-auth              |               |
|        | GET|HEAD api/locations/list                                   | api.locations.list                | Controllers\Admin\LocationsController@getDatatable                | admin-auth              |               |
|        | GET|HEAD api/locations/{locationID}/view                      | api.locations.view                | Controllers\Admin\LocationsController@getDataView                 | admin-auth              |               |
|        | GET|HEAD api/locations/{locationID}/users                     | api.locations.viewusers           | Controllers\Admin\LocationsController@getDataViewUsers            | admin-auth              |               |
|        | GET|HEAD api/locations/{locationID}/assets                    | api.locations.viewassets          | Controllers\Admin\LocationsController@getDataViewAssets           | admin-auth              |               |
|        | GET|HEAD api/depreciations/list                               | api.depreciations.list            | Controllers\Admin\DepreciationsController@getDatatable            | admin-auth              |               |
|        | GET|HEAD api/depreciations/{$depreciationID}/view             | api.depreciations.view            | Controllers\Admin\DepreciationsController@getDataView             | admin-auth              |               |
|        | GET|HEAD api/manufacturers/list                               | api.manufacturers.list            | Controllers\Admin\ManufacturersController@getDatatable            | admin-auth              |               |
|        | GET|HEAD api/manufacturers/{manufacturerID}/view              | api.manufacturers.view            | Controllers\Admin\ManufacturersController@getDataView             | admin-auth              |               |
|        | GET|HEAD api/suppliers/list                                   | api.suppliers.list                | Controllers\Admin\SuppliersController@getDatatable                | admin-auth              |               |
|        | POST api/users                                                | api.users.store                   | Controllers\Admin\UsersController@store                           | admin-auth              |               |
|        | GET|HEAD api/users/list/{status?}                             | api.users.list                    | Controllers\Admin\UsersController@getDatatable                    | admin-auth              |               |
|        | GET|HEAD api/groups/list                                      | api.groups.list                   | Controllers\Admin\GroupsController@getDatatable                   | admin-auth              |               |
|        | GET|HEAD api/licenses/list                                    | api.licenses.list                 | Controllers\Admin\LicensesController@getDatatable                 | admin-auth              |               |
|        | GET|HEAD api/locations                                        | api.locations...index             | Controllers\Admin\LocationsController@index                       | admin-auth              |               |
|        | GET|HEAD api/locations/create                                 | api.locations...create            | Controllers\Admin\LocationsController@create                      | admin-auth              |               |
|        | POST api/locations                                            | api.locations...store             | Controllers\Admin\LocationsController@store                       | admin-auth              |               |
|        | GET|HEAD api/locations/{}                                     | api.locations...show              | Controllers\Admin\LocationsController@show                        | admin-auth              |               |
|        | GET|HEAD api/locations/{}/edit                                | api.locations...edit              | Controllers\Admin\LocationsController@edit                        | admin-auth              |               |
|        | PUT api/locations/{}                                          | api.locations...update            | Controllers\Admin\LocationsController@update                      | admin-auth              |               |
|        | PATCH api/locations/{}                                        |                                   | Controllers\Admin\LocationsController@update                      | admin-auth              |               |
|        | DELETE api/locations/{}                                       | api.locations...destroy           | Controllers\Admin\LocationsController@destroy                     | admin-auth              |               |
|        | GET|HEAD api/locations/{locationID}/check                     |                                   | Closure                                                           | admin-auth              |               |
|        | GET|HEAD api/asset_maintenances/list                          | api.asset_maintenances.list       | Controllers\Admin\AssetMaintenancesController@getDatatable        | admin-auth              |               |
|        | GET|HEAD api/models                                           | api.models...index                | Controllers\Admin\ModelsController@index                          | admin-auth              |               |
|        | GET|HEAD api/models/create                                    | api.models...create               | Controllers\Admin\ModelsController@create                         | admin-auth              |               |
|        | POST api/models                                               | api.models...store                | Controllers\Admin\ModelsController@store                          | admin-auth              |               |
|        | GET|HEAD api/models/{}                                        | api.models...show                 | Controllers\Admin\ModelsController@show                           | admin-auth              |               |
|        | GET|HEAD api/models/{}/edit                                   | api.models...edit                 | Controllers\Admin\ModelsController@edit                           | admin-auth              |               |
|        | PUT api/models/{}                                             | api.models...update               | Controllers\Admin\ModelsController@update                         | admin-auth              |               |
|        | PATCH api/models/{}                                           |                                   | Controllers\Admin\ModelsController@update                         | admin-auth              |               |
|        | DELETE api/models/{}                                          | api.models...destroy              | Controllers\Admin\ModelsController@destroy                        | admin-auth              |               |
|        | GET|HEAD api/models/list/{status?}                            | api.models.list                   | Controllers\Admin\ModelsController@getDatatable                   | admin-auth              |               |
|        | GET|HEAD api/models/{modelID}/view                            | api.models.view                   | Controllers\Admin\ModelsController@getDataView                    | admin-auth              |               |
|        | GET|HEAD api/categories/list                                  | api.categories.list               | Controllers\Admin\CategoriesController@getDatatable               | admin-auth              |               |
|        | GET|HEAD api/categories/{categoryID}/view                     | api.categories.view               | Controllers\Admin\CategoriesController@getDataView                | admin-auth              |               |
|        | GET|HEAD api/suppliers                                        | api.suppliers...index             | Controllers\Admin\SuppliersController@index                       | admin-auth              |               |
|        | GET|HEAD api/suppliers/create                                 | api.suppliers...create            | Controllers\Admin\SuppliersController@create                      | admin-auth              |               |
|        | POST api/suppliers                                            | api.suppliers...store             | Controllers\Admin\SuppliersController@store                       | admin-auth              |               |
|        | GET|HEAD api/suppliers/{}                                     | api.suppliers...show              | Controllers\Admin\SuppliersController@show                        | admin-auth              |               |
|        | GET|HEAD api/suppliers/{}/edit                                | api.suppliers...edit              | Controllers\Admin\SuppliersController@edit                        | admin-auth              |               |
|        | PUT api/suppliers/{}                                          | api.suppliers...update            | Controllers\Admin\SuppliersController@update                      | admin-auth              |               |
|        | PATCH api/suppliers/{}                                        |                                   | Controllers\Admin\SuppliersController@update                      | admin-auth              |               |
|        | DELETE api/suppliers/{}                                       | api.suppliers...destroy           | Controllers\Admin\SuppliersController@destroy                     | admin-auth              |               |
|        | GET|HEAD hardware/create/{model?}                             | create/hardware                   | Controllers\Admin\AssetsController@getCreate                      | admin-auth              |               |
|        | POST hardware/create                                          | savenew/hardware                  | Controllers\Admin\AssetsController@postCreate                     | admin-auth              |               |
|        | GET|HEAD hardware/{assetId}/edit                              | update/hardware                   | Controllers\Admin\AssetsController@getEdit                        | admin-auth              |               |
|        | GET|HEAD hardware/{assetId}/clone                             | clone/hardware                    | Controllers\Admin\AssetsController@getClone                       | admin-auth              |               |
|        | POST hardware/{assetId}/clone                                 |                                   | Controllers\Admin\AssetsController@postCreate                     | admin-auth              |               |
|        | GET|HEAD hardware/{assetId}/delete                            | delete/hardware                   | Controllers\Admin\AssetsController@getDelete                      | admin-auth              |               |
|        | GET|HEAD hardware/{assetId}/checkout                          | checkout/hardware                 | Controllers\Admin\AssetsController@getCheckout                    | admin-auth              |               |
|        | POST hardware/{assetId}/checkout                              |                                   | Controllers\Admin\AssetsController@postCheckout                   | admin-auth              |               |
|        | GET|HEAD hardware/{assetId}/checkin/{backto?}                 | checkin/hardware                  | Controllers\Admin\AssetsController@getCheckin                     | admin-auth              |               |
|        | POST hardware/{assetId}/checkin/{backto?}                     |                                   | Controllers\Admin\AssetsController@postCheckin                    | admin-auth              |               |
|        | GET|HEAD hardware/{assetId}/view                              | view/hardware                     | Controllers\Admin\AssetsController@getView                        | admin-auth              |               |
|        | GET|HEAD hardware/{assetId}/qr-view                           | qr-view/hardware                  | Controllers\Admin\AssetsController@getView                        | admin-auth              |               |
|        | GET|HEAD hardware/{assetId}/qr_code                           | qr_code/hardware                  | Controllers\Admin\AssetsController@getQrCode                      | admin-auth              |               |
|        | GET|HEAD hardware/{assetId}/restore                           | restore/hardware                  | Controllers\Admin\AssetsController@getRestore                     | admin-auth              |               |
|        | POST hardware/{assetId}/upload                                | upload/asset                      | Controllers\Admin\AssetsController@postUpload                     | admin-auth              |               |
|        | GET|HEAD hardware/{assetId}/deletefile/{fileId}               | delete/assetfile                  | Controllers\Admin\AssetsController@getDeleteFile                  | admin-auth              |               |
|        | GET|HEAD hardware/{assetId}/showfile/{fileId}                 | show/assetfile                    | Controllers\Admin\AssetsController@displayFile                    | admin-auth              |               |
|        | GET|HEAD hardware/import/delete-import/{filename}             | assets/import/delete-file         | Controllers\Admin\AssetsController@getDeleteImportFile            | admin-auth              |               |
|        | GET|HEAD hardware/import/process/{filename}                   | assets/import/process-file        | Controllers\Admin\AssetsController@getProcessImportFile           | admin-auth              |               |
|        | GET|HEAD hardware/import                                      | assets/import                     | Controllers\Admin\AssetsController@getImportUpload                | admin-auth              |               |
|        | POST hardware/{assetId}/edit                                  |                                   | Controllers\Admin\AssetsController@postEdit                       | admin-auth              |               |
|        | POST hardware/bulkedit                                        | hardware/bulkedit                 | Controllers\Admin\AssetsController@postBulkEdit                   | admin-auth              |               |
|        | POST hardware/bulkdelete                                      | hardware/bulkdelete               | Controllers\Admin\AssetsController@postBulkDelete                 | admin-auth              |               |
|        | POST hardware/bulksave                                        | hardware/bulksave                 | Controllers\Admin\AssetsController@postBulkSave                   | admin-auth              |               |
|        | GET|HEAD hardware/models                                      | models                            | Controllers\Admin\ModelsController@getIndex                       | admin-auth              |               |
|        | GET|HEAD hardware/models/create                               | create/model                      | Controllers\Admin\ModelsController@getCreate                      | admin-auth              |               |
|        | POST hardware/models/create                                   |                                   | Controllers\Admin\ModelsController@postCreate                     | admin-auth              |               |
|        | GET|HEAD hardware/models/{modelId}/edit                       | update/model                      | Controllers\Admin\ModelsController@getEdit                        | admin-auth              |               |
|        | POST hardware/models/{modelId}/edit                           |                                   | Controllers\Admin\ModelsController@postEdit                       | admin-auth              |               |
|        | GET|HEAD hardware/models/{modelId}/clone                      | clone/model                       | Controllers\Admin\ModelsController@getClone                       | admin-auth              |               |
|        | POST hardware/models/{modelId}/clone                          |                                   | Controllers\Admin\ModelsController@postCreate                     | admin-auth              |               |
|        | GET|HEAD hardware/models/{modelId}/delete                     | delete/model                      | Controllers\Admin\ModelsController@getDelete                      | admin-auth              |               |
|        | GET|HEAD hardware/models/{modelId}/view                       | view/model                        | Controllers\Admin\ModelsController@getView                        | admin-auth              |               |
|        | GET|HEAD hardware/models/{modelID}/restore                    | restore/model                     | Controllers\Admin\ModelsController@getRestore                     | admin-auth              |               |
|        | GET|HEAD hardware/models/{modelId}/custom_fields              | custom_fields/model               | Controllers\Admin\ModelsController@getCustomFields                | admin-auth              |               |
|        | GET|HEAD hardware                                             | hardware                          | Controllers\Admin\AssetsController@getIndex                       | admin-auth              |               |
|        | GET|HEAD admin/licenses/create                                | create/licenses                   | Controllers\Admin\LicensesController@getCreate                    | admin-auth              |               |
|        | POST admin/licenses/create                                    |                                   | Controllers\Admin\LicensesController@postCreate                   | admin-auth              |               |
|        | GET|HEAD admin/licenses/{licenseId}/edit                      | update/license                    | Controllers\Admin\LicensesController@getEdit                      | admin-auth              |               |
|        | POST admin/licenses/{licenseId}/edit                          |                                   | Controllers\Admin\LicensesController@postEdit                     | admin-auth              |               |
|        | GET|HEAD admin/licenses/{licenseId}/clone                     | clone/license                     | Controllers\Admin\LicensesController@getClone                     | admin-auth              |               |
|        | POST admin/licenses/{licenseId}/clone                         |                                   | Controllers\Admin\LicensesController@postCreate                   | admin-auth              |               |
|        | GET|HEAD admin/licenses/{licenseId}/delete                    | delete/license                    | Controllers\Admin\LicensesController@getDelete                    | admin-auth              |               |
|        | GET|HEAD admin/licenses/{licenseId}/freecheckout              | freecheckout/license              | Controllers\Admin\LicensesController@getFreeLicense               | admin-auth              |               |
|        | GET|HEAD admin/licenses/{licenseId}/checkout                  | checkout/license                  | Controllers\Admin\LicensesController@getCheckout                  | admin-auth              |               |
|        | POST admin/licenses/{licenseId}/checkout                      |                                   | Controllers\Admin\LicensesController@postCheckout                 | admin-auth              |               |
|        | GET|HEAD admin/licenses/{licenseId}/checkin/{backto?}         | checkin/license                   | Controllers\Admin\LicensesController@getCheckin                   | admin-auth              |               |
|        | POST admin/licenses/{licenseId}/checkin/{backto?}             |                                   | Controllers\Admin\LicensesController@postCheckin                  | admin-auth              |               |
|        | GET|HEAD admin/licenses/{licenseId}/view                      | view/license                      | Controllers\Admin\LicensesController@getView                      | admin-auth              |               |
|        | POST admin/licenses/{licenseId}/upload                        | upload/license                    | Controllers\Admin\LicensesController@postUpload                   | admin-auth              |               |
|        | GET|HEAD admin/licenses/{licenseId}/deletefile/{fileId}       | delete/licensefile                | Controllers\Admin\LicensesController@getDeleteFile                | admin-auth              |               |
|        | GET|HEAD admin/licenses/{licenseId}/showfile/{fileId}         | show/licensefile                  | Controllers\Admin\LicensesController@displayFile                  | admin-auth              |               |
|        | GET|HEAD admin/licenses                                       | licenses                          | Controllers\Admin\LicensesController@getIndex                     | admin-auth              |               |
|        | GET|HEAD admin/asset_maintenances/create/{assetId?}           | create/asset_maintenances         | Controllers\Admin\AssetMaintenancesController@getCreate           | admin-auth              |               |
|        | POST admin/asset_maintenances/create/{assetId?}               |                                   | Controllers\Admin\AssetMaintenancesController@postCreate          | admin-auth              |               |
|        | GET|HEAD admin/asset_maintenances                             | asset_maintenances                | Controllers\Admin\AssetMaintenancesController@getIndex            | admin-auth              |               |
|        | GET|HEAD admin/asset_maintenances/{assetMaintenanceId}/edit   | update/asset_maintenance          | Controllers\Admin\AssetMaintenancesController@getEdit             | admin-auth              |               |
|        | POST admin/asset_maintenances/{assetMaintenanceId}/edit       |                                   | Controllers\Admin\AssetMaintenancesController@postEdit            | admin-auth              |               |
|        | GET|HEAD admin/asset_maintenances/{assetMaintenanceId}/delete | delete/asset_maintenance          | Controllers\Admin\AssetMaintenancesController@getDelete           | admin-auth              |               |
|        | GET|HEAD admin/asset_maintenances/{assetMaintenanceId}/view   | view/asset_maintenance            | Controllers\Admin\AssetMaintenancesController@getView             | admin-auth              |               |
|        | GET|HEAD admin/accessories/create                             | create/accessory                  | Controllers\Admin\AccessoriesController@getCreate                 | admin-auth              |               |
|        | POST admin/accessories/create                                 |                                   | Controllers\Admin\AccessoriesController@postCreate                | admin-auth              |               |
|        | GET|HEAD admin/accessories/{accessoryID}/edit                 | update/accessory                  | Controllers\Admin\AccessoriesController@getEdit                   | admin-auth              |               |
|        | POST admin/accessories/{accessoryID}/edit                     |                                   | Controllers\Admin\AccessoriesController@postEdit                  | admin-auth              |               |
|        | GET|HEAD admin/accessories/{accessoryID}/delete               | delete/accessory                  | Controllers\Admin\AccessoriesController@getDelete                 | admin-auth              |               |
|        | GET|HEAD admin/accessories/{accessoryID}/view                 | view/accessory                    | Controllers\Admin\AccessoriesController@getView                   | admin-auth              |               |
|        | GET|HEAD admin/accessories/{accessoryID}/checkout             | checkout/accessory                | Controllers\Admin\AccessoriesController@getCheckout               | admin-auth              |               |
|        | POST admin/accessories/{accessoryID}/checkout                 |                                   | Controllers\Admin\AccessoriesController@postCheckout              | admin-auth              |               |
|        | GET|HEAD admin/accessories/{accessoryID}/checkin/{backto?}    | checkin/accessory                 | Controllers\Admin\AccessoriesController@getCheckin                | admin-auth              |               |
|        | POST admin/accessories/{accessoryID}/checkin/{backto?}        |                                   | Controllers\Admin\AccessoriesController@postCheckin               | admin-auth              |               |
|        | GET|HEAD admin/accessories                                    | accessories                       | Controllers\Admin\AccessoriesController@getIndex                  | admin-auth              |               |
|        | GET|HEAD admin/consumables/create                             | create/consumable                 | Controllers\Admin\ConsumablesController@getCreate                 | admin-auth              |               |
|        | POST admin/consumables/create                                 |                                   | Controllers\Admin\ConsumablesController@postCreate                | admin-auth              |               |
|        | GET|HEAD admin/consumables/{consumableID}/edit                | update/consumable                 | Controllers\Admin\ConsumablesController@getEdit                   | admin-auth              |               |
|        | POST admin/consumables/{consumableID}/edit                    |                                   | Controllers\Admin\ConsumablesController@postEdit                  | admin-auth              |               |
|        | GET|HEAD admin/consumables/{consumableID}/delete              | delete/consumable                 | Controllers\Admin\ConsumablesController@getDelete                 | admin-auth              |               |
|        | GET|HEAD admin/consumables/{consumableID}/view                | view/consumable                   | Controllers\Admin\ConsumablesController@getView                   | admin-auth              |               |
|        | GET|HEAD admin/consumables/{consumableID}/checkout            | checkout/consumable               | Controllers\Admin\ConsumablesController@getCheckout               | admin-auth              |               |
|        | POST admin/consumables/{consumableID}/checkout                |                                   | Controllers\Admin\ConsumablesController@postCheckout              | admin-auth              |               |
|        | GET|HEAD admin/consumables                                    | consumables                       | Controllers\Admin\ConsumablesController@getIndex                  | admin-auth              |               |
|        | GET|HEAD admin/settings/app                                   | app                               | Controllers\Admin\SettingsController@getIndex                     | admin-auth              |               |
|        | GET|HEAD admin/settings/app/edit                              | edit/settings                     | Controllers\Admin\SettingsController@getEdit                      | admin-auth              |               |
|        | POST admin/settings/app/edit                                  |                                   | Controllers\Admin\SettingsController@postEdit                     | admin-auth              |               |
|        | GET|HEAD admin/settings/backups/download/{filename}           | settings/download-file            | Controllers\Admin\SettingsController@downloadFile                 | admin-auth, backup-auth |               |
|        | GET|HEAD admin/settings/backups/delete/{filename}             | settings/delete-file              | Controllers\Admin\SettingsController@deleteFile                   | admin-auth, backup-auth |               |
|        | POST admin/settings/backups                                   | settings/backups                  | Controllers\Admin\SettingsController@postBackups                  | admin-auth, backup-auth |               |
|        | GET|HEAD admin/settings/backups                               | settings/backups                  | Controllers\Admin\SettingsController@getBackups                   | admin-auth, backup-auth |               |
|        | GET|HEAD admin/settings/companies/{companyId}/edit            | update/company                    | Controllers\Admin\CompaniesController@getEdit                     | admin-auth              |               |
|        | GET|HEAD admin/settings/companies/create                      | create/company                    | Controllers\Admin\CompaniesController@getCreate                   | admin-auth              |               |
|        | GET|HEAD admin/settings/companies                             | companies                         | Controllers\Admin\CompaniesController@getIndex                    | admin-auth              |               |
|        | POST admin/settings/companies/{companyId}/delete              | delete/company                    | Controllers\Admin\CompaniesController@postDelete                  | admin-auth              |               |
|        | POST admin/settings/companies/{companyId}/edit                |                                   | Controllers\Admin\CompaniesController@postEdit                    | admin-auth              |               |
|        | POST admin/settings/companies/create                          |                                   | Controllers\Admin\CompaniesController@postCreate                  | admin-auth              |               |
|        | GET|HEAD admin/settings/manufacturers                         | manufacturers                     | Controllers\Admin\ManufacturersController@getIndex                | admin-auth              |               |
|        | GET|HEAD admin/settings/manufacturers/create                  | create/manufacturer               | Controllers\Admin\ManufacturersController@getCreate               | admin-auth              |               |
|        | POST admin/settings/manufacturers/create                      |                                   | Controllers\Admin\ManufacturersController@postCreate              | admin-auth              |               |
|        | GET|HEAD admin/settings/manufacturers/{manufacturerId}/edit   | update/manufacturer               | Controllers\Admin\ManufacturersController@getEdit                 | admin-auth              |               |
|        | POST admin/settings/manufacturers/{manufacturerId}/edit       |                                   | Controllers\Admin\ManufacturersController@postEdit                | admin-auth              |               |
|        | GET|HEAD admin/settings/manufacturers/{manufacturerId}/delete | delete/manufacturer               | Controllers\Admin\ManufacturersController@getDelete               | admin-auth              |               |
|        | GET|HEAD admin/settings/manufacturers/{manufacturerId}/view   | view/manufacturer                 | Controllers\Admin\ManufacturersController@getView                 | admin-auth              |               |
|        | GET|HEAD admin/settings/suppliers                             | suppliers                         | Controllers\Admin\SuppliersController@getIndex                    | admin-auth              |               |
|        | GET|HEAD admin/settings/suppliers/create                      | create/supplier                   | Controllers\Admin\SuppliersController@getCreate                   | admin-auth              |               |
|        | POST admin/settings/suppliers/create                          |                                   | Controllers\Admin\SuppliersController@postCreate                  | admin-auth              |               |
|        | GET|HEAD admin/settings/suppliers/{supplierId}/edit           | update/supplier                   | Controllers\Admin\SuppliersController@getEdit                     | admin-auth              |               |
|        | POST admin/settings/suppliers/{supplierId}/edit               |                                   | Controllers\Admin\SuppliersController@postEdit                    | admin-auth              |               |
|        | GET|HEAD admin/settings/suppliers/{supplierId}/delete         | delete/supplier                   | Controllers\Admin\SuppliersController@getDelete                   | admin-auth              |               |
|        | GET|HEAD admin/settings/suppliers/{supplierId}/view           | view/supplier                     | Controllers\Admin\SuppliersController@getView                     | admin-auth              |               |
|        | GET|HEAD admin/settings/categories/create                     | create/category                   | Controllers\Admin\CategoriesController@getCreate                  | admin-auth              |               |
|        | POST admin/settings/categories/create                         |                                   | Controllers\Admin\CategoriesController@postCreate                 | admin-auth              |               |
|        | GET|HEAD admin/settings/categories/{categoryId}/edit          | update/category                   | Controllers\Admin\CategoriesController@getEdit                    | admin-auth              |               |
|        | POST admin/settings/categories/{categoryId}/edit              |                                   | Controllers\Admin\CategoriesController@postEdit                   | admin-auth              |               |
|        | GET|HEAD admin/settings/categories/{categoryId}/delete        | delete/category                   | Controllers\Admin\CategoriesController@getDelete                  | admin-auth              |               |
|        | GET|HEAD admin/settings/categories/{categoryId}/view          | view/category                     | Controllers\Admin\CategoriesController@getView                    | admin-auth              |               |
|        | GET|HEAD admin/settings/categories                            | categories                        | Controllers\Admin\CategoriesController@getIndex                   | admin-auth              |               |
|        | GET|HEAD admin/settings/depreciations                         | depreciations                     | Controllers\Admin\DepreciationsController@getIndex                | admin-auth              |               |
|        | GET|HEAD admin/settings/depreciations/create                  | create/depreciations              | Controllers\Admin\DepreciationsController@getCreate               | admin-auth              |               |
|        | POST admin/settings/depreciations/create                      |                                   | Controllers\Admin\DepreciationsController@postCreate              | admin-auth              |               |
|        | GET|HEAD admin/settings/depreciations/{depreciationId}/edit   | update/depreciations              | Controllers\Admin\DepreciationsController@getEdit                 | admin-auth              |               |
|        | POST admin/settings/depreciations/{depreciationId}/edit       |                                   | Controllers\Admin\DepreciationsController@postEdit                | admin-auth              |               |
|        | GET|HEAD admin/settings/depreciations/{depreciationId}/delete | delete/depreciations              | Controllers\Admin\DepreciationsController@getDelete               | admin-auth              |               |
|        | GET|HEAD admin/settings/locations                             | locations                         | Controllers\Admin\LocationsController@getIndex                    | admin-auth              |               |
|        | GET|HEAD admin/settings/locations/create                      | create/location                   | Controllers\Admin\LocationsController@getCreate                   | admin-auth              |               |
|        | POST admin/settings/locations/create                          |                                   | Controllers\Admin\LocationsController@postCreate                  | admin-auth              |               |
|        | GET|HEAD admin/settings/locations/{locationId}/edit           | update/location                   | Controllers\Admin\LocationsController@getEdit                     | admin-auth              |               |
|        | POST admin/settings/locations/{locationId}/edit               |                                   | Controllers\Admin\LocationsController@postEdit                    | admin-auth              |               |
|        | GET|HEAD admin/settings/locations/{locationId}/view           |                                   | Controllers\Admin\LocationsController@getView                     | admin-auth              |               |
|        | GET|HEAD admin/settings/locations/{locationId}/delete         | delete/location                   | Controllers\Admin\LocationsController@getDelete                   | admin-auth              |               |
|        | GET|HEAD admin/settings/statuslabels                          | statuslabels                      | Controllers\Admin\StatuslabelsController@getIndex                 | admin-auth              |               |
|        | GET|HEAD admin/settings/statuslabels/create                   | create/statuslabel                | Controllers\Admin\StatuslabelsController@getCreate                | admin-auth              |               |
|        | POST admin/settings/statuslabels/create                       |                                   | Controllers\Admin\StatuslabelsController@postCreate               | admin-auth              |               |
|        | GET|HEAD admin/settings/statuslabels/{statuslabelId}/edit     | update/statuslabel                | Controllers\Admin\StatuslabelsController@getEdit                  | admin-auth              |               |
|        | POST admin/settings/statuslabels/{statuslabelId}/edit         |                                   | Controllers\Admin\StatuslabelsController@postEdit                 | admin-auth              |               |
|        | GET|HEAD admin/settings/statuslabels/{statuslabelId}/delete   | delete/statuslabel                | Controllers\Admin\StatuslabelsController@getDelete                | admin-auth              |               |
|        | GET|HEAD admin/custom_fields/create-field                     | admin.custom_fields.create-field  | Controllers\Admin\CustomFieldsController@createField              | admin-auth              |               |
|        | POST admin/custom_fields/create-field                         | admin.custom_fields.store-field   | Controllers\Admin\CustomFieldsController@storeField               | admin-auth              |               |
|        | POST admin/custom_fields/{id}/associate                       | admin.custom_fields.associate     | Controllers\Admin\CustomFieldsController@associate                | admin-auth              |               |
|        | DELETE admin/custom_fields/delete-field/{id}                  | admin.custom_fields.delete-field  | Controllers\Admin\CustomFieldsController@deleteField              | admin-auth              |               |
|        | GET|HEAD admin/custom_fields                                  | admin.custom_fields.index         | Controllers\Admin\CustomFieldsController@index                    | admin-auth              |               |
|        | GET|HEAD admin/custom_fields/create                           | admin.custom_fields.create        | Controllers\Admin\CustomFieldsController@create                   | admin-auth              |               |
|        | POST admin/custom_fields                                      | admin.custom_fields.store         | Controllers\Admin\CustomFieldsController@store                    | admin-auth              |               |
|        | GET|HEAD admin/custom_fields/{custom_fields}                  | admin.custom_fields.show          | Controllers\Admin\CustomFieldsController@show                     | admin-auth              |               |
|        | GET|HEAD admin/custom_fields/{custom_fields}/edit             | admin.custom_fields.edit          | Controllers\Admin\CustomFieldsController@edit                     | admin-auth              |               |
|        | PUT admin/custom_fields/{custom_fields}                       | admin.custom_fields.update        | Controllers\Admin\CustomFieldsController@update                   | admin-auth              |               |
|        | PATCH admin/custom_fields/{custom_fields}                     |                                   | Controllers\Admin\CustomFieldsController@update                   | admin-auth              |               |
|        | DELETE admin/custom_fields/{custom_fields}                    | admin.custom_fields.destroy       | Controllers\Admin\CustomFieldsController@destroy                  | admin-auth              |               |
|        | GET|HEAD admin/users/ldap                                     | ldap/user                         | Controllers\Admin\UsersController@getLDAP                         | admin-auth              |               |
|        | POST admin/users/ldap                                         |                                   | Controllers\Admin\UsersController@postLDAP                        | admin-auth              |               |
|        | GET|HEAD admin/users/create                                   | create/user                       | Controllers\Admin\UsersController@getCreate                       | admin-auth              |               |
|        | POST admin/users/create                                       |                                   | Controllers\Admin\UsersController@postCreate                      | admin-auth              |               |
|        | GET|HEAD admin/users/import                                   | import/user                       | Controllers\Admin\UsersController@getImport                       | admin-auth              |               |
|        | POST admin/users/import                                       |                                   | Controllers\Admin\UsersController@postImport                      | admin-auth              |               |
|        | GET|HEAD admin/users/{userId}/edit                            | update/user                       | Controllers\Admin\UsersController@getEdit                         | admin-auth              |               |
|        | POST admin/users/{userId}/edit                                |                                   | Controllers\Admin\UsersController@postEdit                        | admin-auth              |               |
|        | GET|HEAD admin/users/{userId}/clone                           | clone/user                        | Controllers\Admin\UsersController@getClone                        | admin-auth              |               |
|        | POST admin/users/{userId}/clone                               |                                   | Controllers\Admin\UsersController@postCreate                      | admin-auth              |               |
|        | GET|HEAD admin/users/{userId}/delete                          | delete/user                       | Controllers\Admin\UsersController@getDelete                       | admin-auth              |               |
|        | GET|HEAD admin/users/{userId}/restore                         | restore/user                      | Controllers\Admin\UsersController@getRestore                      | admin-auth              |               |
|        | GET|HEAD admin/users/{userId}/view                            | view/user                         | Controllers\Admin\UsersController@getView                         | admin-auth              |               |
|        | GET|HEAD admin/users/{userId}/unsuspend                       | unsuspend/user                    | Controllers\Admin\UsersController@getUnsuspend                    | admin-auth              |               |
|        | POST admin/users/{userId}/upload                              | upload/user                       | Controllers\Admin\UsersController@postUpload                      | admin-auth              |               |
|        | GET|HEAD admin/users/{userId}/deletefile/{fileId}             | delete/userfile                   | Controllers\Admin\UsersController@getDeleteFile                   | admin-auth              |               |
|        | GET|HEAD admin/users/{userId}/showfile/{fileId}               | show/userfile                     | Controllers\Admin\UsersController@displayFile                     | admin-auth              |               |
|        | POST admin/users/bulkedit                                     | users/bulkedit                    | Controllers\Admin\UsersController@postBulkEdit                    | admin-auth              |               |
|        | POST admin/users/bulksave                                     | users/bulksave                    | Controllers\Admin\UsersController@postBulkSave                    | admin-auth              |               |
|        | GET|HEAD admin/users                                          | users                             | Controllers\Admin\UsersController@getIndex                        | admin-auth              |               |
|        | GET|HEAD admin/groups                                         | groups                            | Controllers\Admin\GroupsController@getIndex                       | admin-auth              |               |
|        | GET|HEAD admin/groups/create                                  | create/group                      | Controllers\Admin\GroupsController@getCreate                      | admin-auth              |               |
|        | POST admin/groups/create                                      |                                   | Controllers\Admin\GroupsController@postCreate                     | admin-auth              |               |
|        | GET|HEAD admin/groups/{groupId}/edit                          | update/group                      | Controllers\Admin\GroupsController@getEdit                        | admin-auth              |               |
|        | POST admin/groups/{groupId}/edit                              |                                   | Controllers\Admin\GroupsController@postEdit                       | admin-auth              |               |
|        | GET|HEAD admin/groups/{groupId}/delete                        | delete/group                      | Controllers\Admin\GroupsController@getDelete                      | admin-auth              |               |
|        | GET|HEAD admin/groups/{groupId}/restore                       | restore/group                     | Controllers\Admin\GroupsController@getRestore                     | admin-auth              |               |
|        | GET|HEAD admin/groups/{groupId}/view                          | view/group                        | Controllers\Admin\GroupsController@getView                        | admin-auth              |               |
|        | GET|HEAD admin/dashboard                                      | admin                             | Controllers\Admin\DashboardController@getIndex                    | admin-auth              |               |
|        | GET|HEAD auth/signin                                          | signin                            | AuthController@getSignin                                          |                         |               |
|        | POST auth/signin                                              |                                   | AuthController@postSignin                                         |                         |               |
|        | POST auth/signup                                              |                                   | AuthController@postSignup                                         |                         |               |
|        | GET|HEAD auth/activate/{activationCode}                       | activate                          | AuthController@getActivate                                        |                         |               |
|        | GET|HEAD auth/forgot-password                                 | forgot-password                   | AuthController@getForgotPassword                                  |                         |               |
|        | POST auth/forgot-password                                     |                                   | AuthController@postForgotPassword                                 |                         |               |
|        | GET|HEAD auth/forgot-password/{passwordResetCode}             | forgot-password-confirm           | AuthController@getForgotPasswordConfirm                           |                         |               |
|        | POST auth/forgot-password/{passwordResetCode}                 |                                   | AuthController@postForgotPasswordConfirm                          |                         |               |
|        | GET|HEAD auth/logout                                          | logout                            | AuthController@getLogout                                          |                         |               |
|        | GET|HEAD account/profile                                      | profile                           | Controllers\Account\ProfileController@getIndex                    | auth                    |               |
|        | POST account/profile                                          |                                   | Controllers\Account\ProfileController@postIndex                   | auth                    |               |
|        | GET|HEAD account/change-password                              | change-password                   | Controllers\Account\ChangePasswordController@getIndex             | auth                    |               |
|        | POST account/change-password                                  |                                   | Controllers\Account\ChangePasswordController@postIndex            | auth                    |               |
|        | GET|HEAD account/view-assets                                  | view-assets                       | Controllers\Account\ViewAssetsController@getIndex                 | auth                    |               |
|        | GET|HEAD account/change-email                                 | change-email                      | Controllers\Account\ChangeEmailController@getIndex                | auth                    |               |
|        | POST account/change-email                                     |                                   | Controllers\Account\ChangeEmailController@postIndex               | auth                    |               |
|        | GET|HEAD account/accept-asset/{logID}                         | account/accept-assets             | Controllers\Account\ViewAssetsController@getAcceptAsset           | auth                    |               |
|        | POST account/accept-asset/{logID}                             | account/asset-accepted            | Controllers\Account\ViewAssetsController@postAcceptAsset          | auth                    |               |
|        | GET|HEAD account/requestable-assets                           | requestable-assets                | Controllers\Account\ViewAssetsController@getRequestableIndex      | auth                    |               |
|        | GET|HEAD account/request-asset/{assetId}                      | account/request-asset             | Controllers\Account\ViewAssetsController@getRequestAsset          | auth                    |               |
|        | GET|HEAD account/dashboard                                    | account                           | Controllers\Account\DashboardController@getIndex                  | auth                    |               |
|        | GET|HEAD reports/depreciation                                 | reports/depreciation              | Controllers\Admin\ReportsController@getDeprecationReport          | reporting-auth          |               |
|        | GET|HEAD reports/export/depreciation                          | reports/export/depreciation       | Controllers\Admin\ReportsController@exportDeprecationReport       | reporting-auth          |               |
|        | GET|HEAD reports/asset_maintenances                           | reports/asset_maintenances        | Controllers\Admin\ReportsController@getAssetMaintenancesReport    | reporting-auth          |               |
|        | GET|HEAD reports/export/asset_maintenances                    | reports/export/asset_maintenances | Controllers\Admin\ReportsController@exportAssetMaintenancesReport | reporting-auth          |               |
|        | GET|HEAD reports/licenses                                     | reports/licenses                  | Controllers\Admin\ReportsController@getLicenseReport              | reporting-auth          |               |
|        | GET|HEAD reports/export/licenses                              | reports/export/licenses           | Controllers\Admin\ReportsController@exportLicenseReport           | reporting-auth          |               |
|        | GET|HEAD reports/assets                                       | reports/assets                    | Controllers\Admin\ReportsController@getAssetsReport               | reporting-auth          |               |
|        | GET|HEAD reports/export/assets                                | reports/export/assets             | Controllers\Admin\ReportsController@exportAssetReport             | reporting-auth          |               |
|        | GET|HEAD reports/accessories                                  | reports/accessories               | Controllers\Admin\ReportsController@getAccessoryReport            | reporting-auth          |               |
|        | GET|HEAD reports/export/accessories                           | reports/export/accessories        | Controllers\Admin\ReportsController@exportAccessoryReport         | reporting-auth          |               |
|        | GET|HEAD reports/custom                                       | reports/custom                    | Controllers\Admin\ReportsController@getCustomReport               | reporting-auth          |               |
|        | POST reports/custom                                           |                                   | Controllers\Admin\ReportsController@postCustom                    | reporting-auth          |               |
|        | GET|HEAD reports/activity                                     | reports/activity                  | Controllers\Admin\ReportsController@getActivityReport             | reporting-auth          |               |
|        | GET|HEAD reports/unaccepted_assets                            | reports/unaccepted_assets         | Controllers\Admin\ReportsController@getAssetAcceptanceReport      | reporting-auth          |               |
|        | GET|HEAD reports/export/unaccepted_assets                     | reports/export/unaccepted_assets  | Controllers\Admin\ReportsController@exportAssetAcceptanceReport   | reporting-auth          |               |
|        | GET|HEAD dashboard                                            | home                              | Controllers\Admin\DashboardController@getIndex                    | admin-auth              |               |
|        | GET|HEAD /                                                    | map                               | Controllers\Admin\DashboardController@getMap                      | admin-auth              |               |
|        | GET|HEAD map/mapdata                                          | map                               | Controllers\Admin\DashboardController@fetchMapData                | admin-auth              |               |
+--------+---------------------------------------------------------------+-----------------------------------+-------------------------------------------------------------------+-------------------------+---------------+

D:\WORK\PHP\ams>